export const playlistNames = [
  "Lofi Hip Hop Beats",
  "Chill Lofi Study",
  "Sleep Music",
  "Relaxing Piano",
  "Deep Focus",
  "Peaceful Piano",
  "Lofi Chill",
  "Study Beats",
  "Calm Vibes",
  "Rainy Day Jazz",
  "Coffee Shop Vibes",
  "Midnight Lofi",
  "Chill Beats",
  "Ambient Study",
  "Acoustic Chill",
  "Late Night Vibes",
  "Downtempo Beats",
  "Meditation Music",
  "Soft Pop Hits",
  "Indie Folk",
  "Jazz Vibes",
  "Bedroom Pop",
  "Mellow Bars",
  "Chillhop",
  "Lo-fi Beats",
  "Instrumental Study",
  "Chill Indie",
  "Relaxing Guitar",
  "Ambient Chill",
  "Focus Flow",
  "Brain Food",
  "Night Rider",
  "Dreamy Vibes",
  "Sad Songs",
  "Emotional Piano",
  "Breakup Songs",
  "Mood Booster",
  "Feel Good Indie",
  "Morning Coffee",
  "Sunday Morning",
  "Lazy Sunday",
  "Cozy Nights",
  "Bedroom Beats",
  "Study Session",
  "Concentration Music",
  "Productive Morning",
  "Evening Acoustic",
  "Sunset Vibes",
  "Nighttime Jazz",
  "Sleepy Lofi",
  "Calm Piano",
  "Instrumental Beats",
  "Chillwave",
  "Synthwave Chill",
  "R&B Chill",
  "Soul Music",
  "Smooth Jazz",
  "Neo Soul",
  "Alternative R&B",
  "Indie Vibes",
  "Bedroom Indie",
  "Chill Rap",
  "Mellow Hip Hop",
  "Late Night Drive",
  "Night Drive",
  "Rainy Mood",
  "Rain Sounds",
  "Nature Sounds",
  "White Noise",
  "Ambient Soundscape",
  "Study Music",
  "Reading Music",
  "Work From Home",
  "Background Music",
  "Soft Instrumental",
  "Chill Study Beats",
  "Homework Playlist",
  "Exam Study",
  "Focus Music",
  "Deep Work",
  "Productivity Playlist",
  "Calm Study",
  "Library Sounds",
  "Coffee House Jazz",
  "Cafe Music",
  "Bossa Nova",
  "Smooth Bossa",
  "Acoustic Covers",
  "Unplugged",
  "Stripped Down",
  "Raw Acoustic",
  "Singer Songwriter",
  "Sad Indie",
  "Melancholy Mood",
  "Heartbreak Playlist",
  "Moving On",
  "Self Care",
  "Mental Health",
  "Healing Music",
  "Rock Classics",
  "Alternative Rock",
  "Indie Rock",
  "Pop Hits",
  "Top Pop",
  "Dance Party",
  "EDM Bangers",
  "House Music",
  "Techno Vibes",
  "Drum and Bass",
  "Dubstep",
  "Trap Nation",
  "Hip Hop Classics",
  "Rap Caviar",
  "Old School Hip Hop",
  "90s Hip Hop",
  "Underground Rap",
  "Conscious Hip Hop",
  "Jazz Classics",
  "Smooth Jazz",
  "Blues Music",
  "Classic Rock",
  "Hard Rock",
  "Metal Hits",
  "Punk Rock",
  "Emo Classics",
  "Pop Punk",
  "Country Hits",
  "Country Roads",
  "Modern Country",
  "Outlaw Country",
  "Folk Music",
  "Americana",
  "Bluegrass",
  "Gospel Music",
  "Worship Songs",
  "Christian Rock",
  "Reggae Vibes",
  "Dancehall",
  "Afrobeats",
  "Latin Hits",
  "Reggaeton",
  "Salsa Music",
  "Bachata",
  "K-Pop Hits",
  "J-Pop",
  "Anime Music",
  "Video Game Music",
  "Movie Soundtracks",
  "Classical Music",
  "Baroque",
  "Romantic Era",
  "Opera",
  "Orchestra",
  "Symphony",
  "Chamber Music",
  "Funk Music",
  "Disco Hits",
  "80s Hits",
  "90s Nostalgia",
  "2000s Throwbacks",
  "Throwback Thursday",
  "Retro Vibes",
  "New Wave",
  "Synthpop",
  "Shoegaze",
  "Dream Pop",
  "Post Rock",
  "Math Rock",
  "Prog Rock",
  "Psychedelic Rock",
  "Garage Rock",
  "Surf Rock",
  "Rockabilly",
  "Grunge",
  "Britpop",
  "Indie Pop",
  "Electropop",
  "Future Bass",
  "Trance Music",
  "Progressive House",
  "Deep House",
  "Tropical House",
  "Bass House",
  "Hardstyle",
  "Hardcore",
  "Breakbeat",
  "Jungle",
  "Liquid DnB",
  "Neurofunk",
  "Ambient Techno",
  "Minimal Techno",
  "Detroit Techno",
  "Berlin Techno",
  "UK Garage",
  "Grime",
  "Drill Music",
  "Phonk",
  "Cloud Rap",
  "Boom Bap",
  "Jazz Rap",
  "Trip Hop",
  "Downtempo",
  "Acid Jazz",
  "Nu Jazz",
  "Latin Jazz",
  "Bossa Nova Jazz",
  "Swing Music",
  "Big Band",
  "Bebop",
  "Cool Jazz",
  "Free Jazz",
  "Fusion Jazz",
  "Soul Classics",
  "Motown",
  "Northern Soul",
  "Southern Soul",
  "New Jack Swing",
  "Quiet Storm",
  "Contemporary R&B",
  "Alt R&B",
  "PBR&B",
  "Funk Soul",
  "Acid Rock",
  "Stoner Rock",
  "Doom Metal",
  "Black Metal",
  "Death Metal",
  "Thrash Metal",
  "Power Metal",
  "Symphonic Metal",
  "Nu Metal",
  "Metalcore",
  "Post Hardcore",
  "Screamo",
  "Ska Punk",
  "Celtic Punk",
  "Folk Punk",
  "Cowpunk",
  "Honky Tonk",
  "Western Swing",
  "Tejano Music",
  "Cumbia",
  "Merengue",
  "Bossa Nova",
  "Samba",
  "MPB",
  "Fado",
  "Flamenco",
  "Tango",
  "Mariachi",
  "Ranchera",
  "Norteño",
  "Banda",
  "Corridos",
  "Tropical",
  "Soca",
  "Calypso",
  "Zouk",
  "Highlife",
  "Juju Music",
  "Soukous",
  "Mbalax",
  "Kwaito",
  "Amapiano",
  "Gqom",
  "Baile Funk",
  "Pagode",
  "Axé",
  "Forró",
  "Bolero",
  "Son Cubano",
  "Mambo",
  "Cha Cha Cha",
  "Rumba",
  "Timba",
  "Vallenato",
  "Champeta",
  "Porro",
  "Bullerengue"
];