export const playlistNames = [
  "beats that help me sleep fr",
  "chill lofi for when life's too much",
  "my 3am can't sleep playlist",
  "fuzzy beats to forget your ex",
  "songs for staring at the ceiling",
  "lofi that got me through finals week",
  "rainy day vibes + sad beats",
  "music for overthinking at midnight",
  "literally just vibing rn",
  "sounds that make my brain shut up",
  "lofi + coffee = my morning ritual",
  "slow jams that heal my soul",
  "beats for zoning out completely",
  "songs that feel like a warm hug",
  "the playlist that saved my mental health",
  "my brain on airplane mode",
  "background noise for anxious days",
  "tunes that made me put my phone down",
  "study beats that actually helped",
  "sounds for when words are too much",
  "my 'please just let me sleep' mix",
  "book reading + these beats = heaven",
  "focus mode: activated",
  "night owl soundtrack (insomnia edition)",
  "beats that finally helped me nap",
  "music for when i need space",
  "lofi corner of my messy room",
  "floating away from my problems",
  "sounds that make deadlines less scary",
  "the 'deep breath in, deep breath out' playlist",
  "beats for when my mind won't stop",
  "songs that tuck me in at night",
  "cozy vibes only (no sad stuff allowed)",
  "rainy window + these songs = peace",
  "finally sleeping through the night",
  "focus fuel for impossible assignments",
  "piano beats that feel like therapy",
  "lofi that feels like someone gets it",
  "5 minute mental breaks on repeat",
  "beats that make my studio feel safe",
  "home alone + these vibes = perfect",
  "sounds for reset days",
  "slowing down my racing thoughts",
  "comfort songs collection (tested & approved)",
  "sunday morning peace & quiet",
  "whisper beats for thin walls",
  "my daily unwind ritual",
  "daydreaming fuel for boring days",
  "floating in space but make it cozy",
  "good vibes only (i mean it this time)",
  "lo-fi beats my therapist would approve of",
  "sounds for when i'm ghosting everyone",
  "music that makes homework suck less",
  "my 2am thoughts but make it chill",
  "beats that drown out my roommate",
  "what my depression listens to",
  "the 'i should be sleeping' playlist",
  "songs that make me forget my phone exists",
  "lofi + rain = my happy place",
  "beats for when everything's too loud",
  "the 'finally cleaned my room' soundtrack",
  "stuff that kept me sane last semester",
  "music for cooking alone at midnight",
  "the 'just got rejected' healing playlist",
  "my brain on low battery mode",
  "soundtrack for pretending to be productive",
  "melodies that feel like a weighted blanket",
  "beats for ignoring texts on purpose",
  "lofi that hits different after midnight",
  "when you need to chill tf out",
  "sounds for sunday scaries",
  "helped me survive another monday",
  "lofi + candles = self care night",
  "my 'too tired to function' mix",
  "music that feels like nobody's watching",
  "beats to make your apartment feel bigger",
  "songs that saved me from doom scrolling",
  "the 'i'll start tomorrow' playlist",
  "vibes my plants grow better to",
  "soundtrack for staring out windows",
  "my brain finally shutting up",
  "lofi for when everyone's asleep but me",
  "beats that make me forget deadlines exist",
  "music for fake studying in cafes",
  "sounds for those 'i'm fine' days when i'm not",
  "playlist that got me through that breakup",
  "lofi that feels like being hugged",
  "music for when words are hard",
  "my 'do not disturb' soundtrack",
  "beats that make my commute bearable",
  "songs for drowning out my thoughts",
  "the 'just breathe' collection",
  "vibes for my main character moments",
  "calm beats my anxiety hates",
  "sounds for those nights that never end",
  "the playlist that fixed my sleep schedule",
  "lofi better than my ex's playlists",
  "beats that make homework feel less awful",
  "music for staying up way too late",
  "sounds that temporarily fix everything"
];